---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: not ansible_check_mode

- name: Install required packages
  ansible.builtin.apt:
    name:
      - net-tools
      - python3-pip
      - lldpd
      - pipx
      - unzip
      - curl
      - wget
      